
export const ROUTE_LOGIN = '/login'
export const ROUTE_GOOGLE_AUTH = '/google-auth'
export const ROUTE_REGISTER= '/register'
export const ROUTE_GET_USER = '/user'
export const ROUTE_QUIZ_QUESTIONS = '/quiz/questions'
export const ROUTE_GET_QUIZ = '/quiz'
export const ROUTE_POST_QUESTION = '/question'
export const ROUTE_POST_QUIZ = '/quiz'
export const ROUTE_EDIT_QUESTION = '/question'
export const ROUTE_QUIZ_RESPONSE = '/quiz/response'
export const ROUTE_QUIZES = '/quizes'
export const ROUTE_ADD_CANDIDATE = '/quiz/addCandidate'
export const ROUTE_RESPONSE_UPDATE_TIME = '/response/updateTime'
export const ROUTE_RESPONSE_QUIZ = '/response/quiz'
export const ROUTE_RESPONSE_START = '/response/start'
export const ROUTE_RESPONSE= '/response'